export { Navigation } from './Navigation';
export { Hero } from './Hero';
export { Projects } from './Projects';
export { ProjectsPage } from './ProjectsPage';
export { Principles } from './Principles';
export { Capabilities } from './Capabilities';
export { Resume } from './Resume';
export { Contact } from './Contact';
export { Footer } from './Footer';
