import { Project } from '@/components/sections/ProjectCard';

export const projects: Project[] = [
  {
    id: 'protein-explorer',
    title: 'Protein Interaction Explorer',
    category: 'Full-stack',
    categoryColor: '#4f7dff',
    description:
      'An interactive web application for parsing, visualizing, and comparing protein structures with AlphaFold coloring schemes, automated contact detection, and exportable analysis reports. Built to streamline structural biology research workflows.',
    link: 'https://protein-io.vercel.app/',
    gradientBg: 'linear-gradient(150deg, #4f7dff, #38bdf8)',
    screenshot: '/protein-interaction-explorer.png',
    timeline: 'June 2026 – August 2026',
    details: {
      role: 'Full-Stack Developer',
      tech: ['Next.js', 'React', 'TypeScript', 'Three.js', 'Mol*', 'Python', 'BioPython', 'Tailwind CSS'],
      highlights: [
        'Multi-format structure loading supporting PDB, CIF, mmCIF, UniProt IDs, and AlphaFold database accessions',
        'Browser-based 3D visualization with Mol* viewer featuring AlphaFold pLDDT confidence coloring',
        'Configurable distance cutoff analysis detecting protein-protein and protein-ligand contacts',
        'Chain-level metadata analysis tracking residue counts, atom composition, and inter-chain interactions',
        'Ligand binding analysis with chemistry validation, contact detection, and binding efficiency scoring',
        'Local-first CPU processing ensuring structure privacy with optional session import/export',
      ],
      images: [
        { src: '/protein-chains.png', description: 'Chain analysis with residue and atom counts per chain' },
        { src: '/protein-ligands.png', description: 'Ligand binding analysis with contact detection and chemistry validation' },
        { src: '/protein-sequence.png', description: 'Secondary structure visualization with helix, sheet, and coil percentages' },
        { src: '/protein-dark.png', description: 'Dark mode interface with structure quality verification' },
      ],
    },
  },
  {
    id: 'gtm-engine',
    title: 'GTM Engine',
    category: 'Contract Work',
    categoryColor: '#4f7dff',
    description:
      'Enterprise-grade go-to-market intelligence platform combining AI-powered lead discovery, multi-stage enrichment pipelines, and automated outreach orchestration. Processes raw operator data into qualified, ICP-matched leads with automated Smartlead campaign deployment.',
    link: '#', // Confidential - no public link
    gradientBg: 'linear-gradient(150deg, #E8A5BB, #f39c5f)',
    screenshot: '/gtm-overview.png',
    timeline: 'June – July 2026',
    details: {
      role: 'Lead Full-Stack Engineer',
      tech: ['Next.js 14', 'TypeScript', 'PostgreSQL', 'Prisma ORM', 'Temporal.io', 'Google Places API', 'Smartlead API', 'Vercel', 'tRPC'],
      highlights: [
        'Autonomous lead refinery processing 42,213 raw operators through 6-stage enrichment pipeline',
        'Google Places API integration for business metadata enrichment and contact discovery',
        '3-tier segmentation strategy (Named+Work Email, Named+Public Email, Unnamed+Public Email) achieving 15% conversion',
        'Temporal.io workflow orchestration managing 300+ daily sync operations with automatic retry logic',
        'Real-time analytics dashboard tracking funnel metrics, ICP scoring, and campaign performance',
        'Smartlead integration auto-deploying 10,323 qualified leads across segmented campaigns',
        'Cost-optimized architecture processing 5,917 name-enriched leads at $0.00 ceiling cost',
      ],
      images: [
        { src: '/gtm-funnel.png', description: 'Different stages of the enrichment pipeline depicting each stage funnel metrics' },
        { src: '/gtm-operators.png', description: 'Enriched operators in the pipeline with filtering and search options' },
        { src: '/gtm-smartlead.png', description: 'Smartlead integration tracking page with different campaigns' },
      ],
    },
  },
  {
    id: 'embedding-search',
    title: 'Embedding Similarity Search',
    category: 'Machine Learning',
    categoryColor: '#4f7dff',
    description:
      'Machine learning-powered protein similarity search engine using transformer-based embeddings and vector databases. Enables researchers to discover biologically similar proteins from sequence data, bypassing traditional BLAST alignment limitations.',
    link: 'https://frontend-five-dusky-60.vercel.app/',
    gradientBg: 'linear-gradient(150deg, #38bdf8, #0891b2)',
    screenshot: '/protein-embedding-workbench.png',
    timeline: 'November 2024',
    details: {
      role: 'ML Engineer & Full-Stack Developer',
      tech: ['React', 'FastAPI', 'Python', 'ProtTrans (ESM-2)', 'FAISS', 'NumPy', 'Hugging Face Transformers', 'Docker'],
      highlights: [
        'ESM-2 t6 transformer model generating 320-dimensional pooled sequence embeddings',
        'SQLite vector store caching processed proteins for instant retrieval and comparison',
        'Side-by-side protein comparison interface computing cosine similarity scores',
        'Top-K semantic search returning biologically similar proteins ranked by embedding distance',
        'Accession number and raw sequence input supporting flexible protein lookup methods',
        'HuggingFace Spaces-hosted API providing scalable embedding generation infrastructure',
      ],
      images: [
        { src: '/embedding-compare.png', description: 'Side-by-side protein comparison with cosine similarity scoring' },
        { src: '/embedding-search.png', description: 'Similarity search interface returning top-K ranked matches' },
        { src: '/embedding-cache.png', description: 'Cache statistics showing embedding storage and model backend' },
      ],
    },
  },
  {
    id: 'energy-emissions',
    title: 'Energy & Carbon Emissions',
    category: 'Data Science',
    categoryColor: '#4f7dff',
    description:
      'Statistical modeling project predicting renewable energy output and estimating causal impact of electricity pricing on carbon emissions. Combines time-series forecasting with causal inference to inform energy policy decisions.',
    link: 'https://github.com/can-karakoc/data102-final-proj',
    gradientBg: 'linear-gradient(150deg, #4f7dff, #6d5ef0)',
    mockup: 'paper',
    timeline: 'December 2024',
    details: {
      role: 'Data Scientist & Researcher',
      tech: ['Python', 'Pandas', 'Scikit-learn', 'Statsmodels', 'Matplotlib', 'Seaborn', 'Jupyter Notebooks'],
      highlights: [
        'Generalized Linear Model predicting state-level renewable energy production using 8 environmental and policy features',
        'Causal inference via Difference-in-Differences estimating electricity price impact on carbon emissions',
        'Multi-source data aggregation combining climate data, political metrics, and infrastructure characteristics',
        'State-level granularity analysis covering temperature, sunlight, wind/water resources, and urbanization',
        'Feature set incorporating average annual temperature, political leaning, power plant density, and electricity pricing',
        'Policy-focused insights examining renewable adoption drivers across U.S. states',
      ],
    },
  },
  {
    id: 'lentivirus-search',
    title: 'Lentivirus Gene Search Tool',
    category: 'Genomics',
    categoryColor: '#4f7dff',
    description:
      'Specialized genome browser for lentivirus research, enabling interactive exploration of HIV-1, HIV-2, and SIV genomes. Features gene annotations, conserved region identification, and integrated 3D protein structure visualization for virological research.',
    link: 'https://github.com/JORDANKLANFER/jbrowse2_project',
    gradientBg: 'linear-gradient(150deg, #5C9A92, #6BB2BC)',
    mockup: 'genome',
    timeline: 'October 2024',
    details: {
      role: 'Bioinformatics Developer',
      tech: ['JBrowse 2', 'React', 'TypeScript', 'Python', 'BioPython', 'NCBI Datasets', 'AlphaFold API', 'Mol*'],
      highlights: [
        'JBrowse 2 genome browser deployment for interactive lentivirus genome exploration',
        'Multi-strain reference genome configuration supporting HIV-1, HIV-2, and SIV variants',
        'Apache HTTP server setup enabling web-based genome visualization and navigation',
        'Sequence alignment integration using Minimap2 and SAMtools for genomic analysis',
        'Gene annotation display with searchable track features for viral genome elements',
        'Node.js-based CLI tooling (@jbrowse/cli) for genome browser configuration and management',
      ],
    },
  },
  {
    id: 'email-classification',
    title: 'Email Classification',
    category: 'Machine Learning',
    categoryColor: '#4f7dff',
    description:
      'Binary classification system for spam email detection using logistic regression with extensive feature engineering. Implements L1/L2 regularization and k-fold cross-validation to achieve robust generalization on unseen email data.',
    link: 'https://github.com/can-karakoc/spam-ham.git',
    gradientBg: 'linear-gradient(150deg, #6FAF85, #8BC99F)',
    mockup: 'inbox',
    timeline: 'September 2024',
    details: {
      role: 'Machine Learning Engineer',
      tech: ['Python', 'Scikit-learn', 'Pandas', 'NumPy', 'NLTK', 'Regex', 'Matplotlib', 'Jupyter'],
      highlights: [
        'Binary logistic regression classifier trained on SpamAssassin 2004 public email corpus',
        'Feature engineering extracting word frequency patterns, character ratios, and email structure metrics',
        'L1 (Lasso) and L2 (Ridge) regularization techniques for model generalization and feature selection',
        'K-fold cross-validation framework ensuring robust performance on unseen email data',
        'Spam vs. ham classification distinguishing malicious from legitimate emails',
        'Statistical validation demonstrating classifier effectiveness on real-world email dataset',
      ],
    },
  },
  {
    id: 'world-game-design',
    title: 'World Game Design',
    category: 'Software Engineering',
    categoryColor: '#4f7dff',
    description:
      '2D tile-based exploration game featuring procedurally generated worlds with deterministic seeding. Implements A* pathfinding, room-corridor dungeon generation, and serialization-based save/load system for persistent game state.',
    link: 'https://youtu.be/xaQWofbBags',
    gradientBg: 'linear-gradient(150deg, #95B1EE, #A89FD9)',
    mockup: 'arcade',
    timeline: 'November 2023',
    details: {
      role: 'Software Engineer',
      tech: ['Java', 'Princeton StdDraw', 'JUnit', 'Git', 'OOP Design Patterns'],
      highlights: [
        'Procedural world generation using Perlin noise and BSP tree partitioning',
        'Deterministic pseudo-random seeding enabling reproducible world states',
        'Room-corridor maze algorithm generating connected dungeon layouts',
        'A* pathfinding for NPC movement and player navigation hints',
        'Serialization-based save system persisting game state to disk',
        'Comprehensive JUnit test suite covering edge cases and random seeds',
      ],
    },
  },
];
