import { Project } from '@/components/sections/ProjectCard';

export const projects: Project[] = [
  {
    id: 'protein-explorer',
    title: 'Protein Interaction Explorer',
    category: 'Full-stack',
    categoryColor: 'var(--color-cobalt)',
    description:
      'An interactive web application for parsing, visualizing, and comparing protein structures with AlphaFold coloring schemes, automated contact detection, and exportable analysis reports. Built to streamline structural biology research workflows.',
    link: 'https://protein-io.vercel.app/',
    gradientBg: 'linear-gradient(150deg, #4f7dff, #38bdf8)',
    screenshot: '/protein-interaction-explorer.png',
    timeline: 'June 2026 – August 2026',
    details: {
      role: 'Full-Stack Developer',
      tech: ['Next.js', 'React', 'TypeScript', 'Three.js', 'Mol*', 'Python', 'BioPython', 'Tailwind CSS'],
      highlights: [
        'PDB file parser supporting 50+ structural formats with automatic validation',
        '3D molecular visualization using Mol* viewer with customizable rendering schemes',
        'AlphaFold pLDDT confidence score coloring mapped to structure quality',
        'Automated contact detection algorithm identifying amino acid interactions within 5Å threshold',
        'Side-by-side structure comparison tool for analyzing conformational changes',
        'CSV/JSON export functionality for downstream computational analysis',
      ],
      images: [
        { src: '/protein-chains.png', description: 'Chain analysis with residue and atom counts per chain' },
        { src: '/protein-ligands.png', description: 'Ligand binding analysis with contact detection and chemistry validation' },
        { src: '/protein-sequence.png', description: 'Secondary structure visualization with helix, sheet, and coil percentages' },
        { src: '/protein-dark.png', description: 'Dark mode interface with structure quality verification' },
      ],
    },
  },
  {
    id: 'gtm-engine',
    title: 'GTM Engine',
    category: 'Contract Work',
    categoryColor: 'var(--color-pink)',
    description:
      'Enterprise-grade go-to-market intelligence platform combining AI-powered lead discovery, multi-stage enrichment pipelines, and automated outreach orchestration. Processes raw operator data into qualified, ICP-matched leads with automated Smartlead campaign deployment.',
    link: '#', // Confidential - no public link
    gradientBg: 'linear-gradient(150deg, #E8A5BB, #f39c5f)',
    screenshot: '/gtm-overview.png',
    timeline: 'June – July 2026',
    details: {
      role: 'Lead Full-Stack Engineer',
      tech: ['Next.js 14', 'TypeScript', 'PostgreSQL', 'Prisma ORM', 'Temporal.io', 'Google Places API', 'Smartlead API', 'Vercel', 'tRPC'],
      highlights: [
        'Autonomous lead refinery processing 42,213 raw operators through 6-stage enrichment pipeline',
        'Google Places API integration for business metadata enrichment and contact discovery',
        '3-tier segmentation strategy (Named+Work Email, Named+Public Email, Unnamed+Public Email) achieving 15% conversion',
        'Temporal.io workflow orchestration managing 300+ daily sync operations with automatic retry logic',
        'Real-time analytics dashboard tracking funnel metrics, ICP scoring, and campaign performance',
        'Smartlead integration auto-deploying 10,323 qualified leads across segmented campaigns',
        'Cost-optimized architecture processing 5,917 name-enriched leads at $0.00 ceiling cost',
      ],
      images: [
        { src: '/gtm-smartlead.png', description: 'Smartlead campaign integration with automated lead deployment' },
        { src: '/gtm-operators.png', description: 'Operator pipeline showing 6-stage enrichment workflow' },
        { src: '/gtm-funnel.png', description: 'Analytics dashboard tracking funnel metrics and conversion rates' },
      ],
    },
  },
  {
    id: 'embedding-search',
    title: 'Embedding Similarity Search',
    category: 'Machine Learning',
    categoryColor: 'var(--color-aqua-teal)',
    description:
      'Machine learning-powered protein similarity search engine using transformer-based embeddings and vector databases. Enables researchers to discover biologically similar proteins from sequence data, bypassing traditional BLAST alignment limitations.',
    link: 'https://frontend-five-dusky-60.vercel.app/',
    gradientBg: 'linear-gradient(150deg, #38bdf8, #0891b2)',
    screenshot: '/protein-embedding-workbench.png',
    timeline: 'November 2024',
    details: {
      role: 'ML Engineer & Full-Stack Developer',
      tech: ['React', 'FastAPI', 'Python', 'ProtTrans (ESM-2)', 'FAISS', 'NumPy', 'Hugging Face Transformers', 'Docker'],
      highlights: [
        'ESM-2 protein language model generating 1280-dimensional sequence embeddings',
        'FAISS vector database indexing 50,000+ protein embeddings for sub-second retrieval',
        'Cosine similarity search returning top-K matches ranked by biological relevance',
        'Interactive visualization of embedding space using dimensionality reduction (t-SNE)',
        'REST API serving 100+ queries/minute with sub-500ms p95 latency',
        'Functional annotation transfer based on homology-independent similarity scores',
      ],
    },
  },
  {
    id: 'energy-emissions',
    title: 'Energy & Carbon Emissions',
    category: 'Data Science',
    categoryColor: 'var(--color-cobalt-deep)',
    description:
      'Statistical modeling project predicting renewable energy output and estimating causal impact of electricity pricing on carbon emissions. Combines time-series forecasting with causal inference to inform energy policy decisions.',
    link: 'https://github.com/can-karakoc/data102-final-proj',
    gradientBg: 'linear-gradient(150deg, #4f7dff, #6d5ef0)',
    mockup: 'paper',
    timeline: 'December 2024',
    details: {
      role: 'Data Scientist & Researcher',
      tech: ['Python', 'Pandas', 'Scikit-learn', 'Statsmodels', 'Matplotlib', 'Seaborn', 'Jupyter Notebooks'],
      highlights: [
        'ARIMA time-series model forecasting solar/wind generation with 92% accuracy (7-day horizon)',
        'Causal inference using Difference-in-Differences estimating price→emissions elasticity',
        'Feature engineering incorporating weather data, historical demand, and capacity factors',
        'L1/L2 regularization preventing overfitting on seasonal patterns',
        'Cross-validation framework testing model robustness across different grid regions',
        'Policy recommendations quantifying emissions reduction from dynamic pricing strategies',
      ],
    },
  },
  {
    id: 'lentivirus-search',
    title: 'Lentivirus Gene Search Tool',
    category: 'Genomics',
    categoryColor: 'var(--color-teal)',
    description:
      'Specialized genome browser for lentivirus research, enabling interactive exploration of HIV-1, HIV-2, and SIV genomes. Features gene annotations, conserved region identification, and integrated 3D protein structure visualization for virological research.',
    link: 'https://github.com/JORDANKLANFER/jbrowse2_project',
    gradientBg: 'linear-gradient(150deg, #5C9A92, #6BB2BC)',
    mockup: 'genome',
    timeline: 'October 2024',
    details: {
      role: 'Bioinformatics Developer',
      tech: ['JBrowse 2', 'React', 'TypeScript', 'Python', 'BioPython', 'NCBI Datasets', 'AlphaFold API', 'Mol*'],
      highlights: [
        'JBrowse 2 genome browser configured for 9 lentivirus reference genomes',
        'Automated gene annotation pipeline extracting ORFs, regulatory elements, and LTRs',
        'Conserved region detection using multi-sequence alignment across HIV-1/2/SIV strains',
        'AlphaFold integration displaying predicted 3D structures for viral proteins (Gag, Pol, Env)',
        'Interactive protein viewer highlighting functional domains and mutation hotspots',
        'Custom tracks visualizing drug resistance mutations and epitope binding sites',
      ],
    },
  },
  {
    id: 'email-classification',
    title: 'Email Classification',
    category: 'Machine Learning',
    categoryColor: 'var(--color-green)',
    description:
      'Binary classification system for spam email detection using logistic regression with extensive feature engineering. Implements L1/L2 regularization and k-fold cross-validation to achieve robust generalization on unseen email data.',
    link: 'https://github.com/can-karakoc/spam-ham.git',
    gradientBg: 'linear-gradient(150deg, #6FAF85, #8BC99F)',
    mockup: 'inbox',
    timeline: 'September 2024',
    details: {
      role: 'Machine Learning Engineer',
      tech: ['Python', 'Scikit-learn', 'Pandas', 'NumPy', 'NLTK', 'Regex', 'Matplotlib', 'Jupyter'],
      highlights: [
        '40+ engineered features including word frequency, character ratios, and structural patterns',
        'TF-IDF vectorization capturing spam-indicative keywords and phrases',
        'L1 (Lasso) regularization for automatic feature selection reducing model complexity',
        'L2 (Ridge) regularization preventing coefficient inflation and improving stability',
        '5-fold cross-validation achieving 96.8% accuracy and 0.94 F1-score on test set',
        'Hyperparameter tuning via grid search optimizing regularization strength',
      ],
    },
  },
  {
    id: 'world-game-design',
    title: 'World Game Design',
    category: 'Software Engineering',
    categoryColor: 'var(--color-indigo-purple)',
    description:
      '2D tile-based exploration game featuring procedurally generated worlds with deterministic seeding. Implements A* pathfinding, room-corridor dungeon generation, and serialization-based save/load system for persistent game state.',
    link: 'https://youtu.be/xaQWofbBags',
    gradientBg: 'linear-gradient(150deg, #95B1EE, #A89FD9)',
    mockup: 'arcade',
    timeline: 'November 2023',
    details: {
      role: 'Software Engineer',
      tech: ['Java', 'Princeton StdDraw', 'JUnit', 'Git', 'OOP Design Patterns'],
      highlights: [
        'Procedural world generation using Perlin noise and BSP tree partitioning',
        'Deterministic pseudo-random seeding enabling reproducible world states',
        'Room-corridor maze algorithm generating connected dungeon layouts',
        'A* pathfinding for NPC movement and player navigation hints',
        'Serialization-based save system persisting game state to disk',
        'Comprehensive JUnit test suite covering edge cases and random seeds',
      ],
    },
  },
];
